export * from "./CoursesPage/CoursesPage";
export * from "./СontactsPage/СontactsPage";
export * from "./PricePage/PricePage";
export * from "./AboutUsPage/AboutUs";
export * from "./ServicesPage/ServicesPage";
export * from "./MainPage/MainPage";
export * from "./NotFoundPage/NotFoundPage";
export * from "./LoginPage/LoginPage";
export * from "./RegisterPage/RegisterPage";
